name: ci
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
  workflow_dispatch: null

permissions: {}

jobs:
  test:

    strategy:
      matrix:
        os:
          - macos-15-intel
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
          - windows-11-arm
          - windows-latest

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: cargo xtask fetch-tests
      - run: cargo test --package glvs-core
